version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
configuration: Release
clone_folder: c:\projects\Sitko.ModelSelector
build_script:
- ps: .\Build.ps1
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: QKpP7MvVx9/bjhose++JuHq9SkYYnYKO8wB5d8cBSE3RQ3SLBwX2Msjgw5w8HOkv
  skip_symbols: true