version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
configuration: Release
clone_folder: c:\projects\Sitko.ModelSelector
build_script:
- ps: .\Build.ps1
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet